# Generated by Django 5.0.4 on 2024-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0002_alter_teachingrecord_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingrecord",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teachingrecord",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
