# Generated by Django 5.0.4 on 2024-05-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0003_teachingrecord_end_time_teachingrecord_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachingrecord",
            name="date_taught",
        ),
    ]
