# Generated by Django 5.0.4 on 2024-05-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty", "0004_remove_teachingrecord_date_taught"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingrecord",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
